name: Deploy AltoIRA Demo
on:
  push:
    branches:
      - master
  workflow_dispatch:  # magically allow triggering from the UI
env:
  GIT_COMMIT: ${{ github.sha }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DUPLO_HOST: https://altoira.duplocloud.net
  DUPLO_TOKEN: ${{ secrets.ALTOIRA_DEMO_DUPLO_TOKEN }}
  DUPLO_TENANT_ID: "a183548a-6a35-4bdf-9ba6-5b0eed073082"
jobs:
  image-demoservice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Docker login
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
      - name: Docker Build
        run: docker build -t "duplocloud/anyservice:demoservice-${GIT_COMMIT}" .
      - name: Docker Push
        run: docker push "duplocloud/anyservice:demoservice-${GIT_COMMIT}"
  deploy-demoservice:
    runs-on: ubuntu-latest
    needs:
      - image-demoservice
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy
        run: |
          curl -Ssf -H 'Content-type: application/json' \
            -H "Authorization: Bearer $DUPLO_TOKEN" -XPOST \
            "${DUPLO_HOST}/subscriptions/$DUPLO_TENANT_ID/ReplicationControllerChange" \
            -d '{
              "Name": "demoservice",
              "Image": "'"duplocloud/anyservice:demoservice-${GIT_COMMIT}"'",
              "AgentPlatform": "7"
            }'
